version: "3.9"
services:
  backend:
    build: ./backend
    container_name: sga-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
  frontend:
    build: ./frontend
    container_name: sga-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=${API_BASE:-http://localhost:8000}
    depends_on:
      - backend
