[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.112.2",
    "pydantic==2.9.1",
    "python-multipart==0.0.9",
    "uvicorn==0.30.6",
]
